### ISSUE TITLE
Css classes via data-win-bind attribute

### ISSUE THREAD

**Issue by pbouzakis** [YuzuJS/WinningJS-todo#11]
Are we able to set classnames inside our jade templates using the data-win-attribute. 
An example case would be to set a class based on a model's type

``` html
<h1 class="product-title" data-win-bind="innerText: name; classname: classOfProduct></h1>
```

classOfProduct would be a getter on the datasource, that returns a different classname based on the type.

If we can do this, is there a property we can use to append a classes and not overwrite?  Or conditionally set a class?

**Comment by domenic** [comment]
Since I am afraid the answer to the last two questions is likely "no", it's a good test case for Knockout integration. Namely, we're already hooking up this `<h1>` to a data source. Could that become a Knockout view model? Or could we create a Knockout view model from it, behind the scenes, and pass that to Knockout?

**Comment by domenic** [comment]
Closing, now that we're using Knockout.
